export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <header>
          header
        </header>
        {children}
        <footer>
          footer
        </footer>
      </body>
    </html>
  )
}
